=== ziapeltagames/wrath-of-the-autarch/text/BookChapter.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Standard InDesign tags. -->

<!-- The default root element of any XML. -->
<!ELEMENT Root ANY>

<!-- A Story usually creates a new text frame. -->
<!ELEMENT Story ANY>

<!-- For table formatting. -->
<!ELEMENT Table ANY>
<!ATTLIST Table aid:trows CDATA #IMPLIED>
<!ATTLIST Table aid:tcols CDATA #IMPLIED>
<!ATTLIST Table aid:table CDATA #IMPLIED>
<!ATTLIST Table xmlns:aid CDATA #IMPLIED>

<!ELEMENT Cell ANY>
<!ATTLIST Cell aid:table CDATA #IMPLIED>
<!ATTLIST Cell aid:crows CDATA #IMPLIED>
<!ATTLIST Cell aid:ccols CDATA #IMPLIED>
<!ATTLIST Cell aid:ccolwidth CDATA #IMPLIED>

<!-- Image import. -->
<!ELEMENT Image ANY>

<!-- Not as standard, but these tags provide
     lots of flexibility in creating design elements. -->
<!ELEMENT chapter ANY>
<!ELEMENT chapref ANY>

<!ELEMENT section ANY>
<!ELEMENT secref ANY>

<!ELEMENT h1 ANY>
<!ELEMENT h2 ANY>
<!ELEMENT h3 ANY>
<!ELEMENT h4 ANY>

<!ELEMENT p1 ANY>
<!ELEMENT p2 ANY>
<!ELEMENT cellp ANY>

<!-- These elements are more specific to RPG texts and Fate. -->
<!ELEMENT example ANY>
<!ELEMENT callout ANY>
<!ELEMENT aspect (#PCDATA)>
<!ELEMENT challenge (#PCDATA)>
<!ELEMENT skill (#PCDATA)>

<!ELEMENT stunt (#PCDATA)>
<!ELEMENT stuntt (#PCDATA)>
<!ELEMENT stuntp ANY>
<!ELEMENT stuntd ANY>

<!-- This is for using the Fate font. -->
<!ELEMENT fate (#PCDATA)>

<!-- General text layout tags. -->
<!ELEMENT term (#PCDATA)>
<!ELEMENT strong (#PCDATA)>
<!ELEMENT book (#PCDATA)>
<!ELEMENT em (#PCDATA)>
<!ELEMENT b (#PCDATA)>
<!ELEMENT i (#PCDATA)>

<!-- Tags for lists. -->
<!ELEMENT ul (#PCDATA|l1|l2|l3)*>
<!ELEMENT l1 (#PCDATA|aspect|term|strong|b|i)*>
<!ELEMENT l2 (#PCDATA|aspect|term|strong|b|i)*>
<!ELEMENT l3 (#PCDATA|aspect|term|strong|b|i)*>

<!ELEMENT development ANY>
<!ELEMENT devel_title ANY>
<!ELEMENT devel_cost ANY>

<!ELEMENT statblock ANY>
<!ELEMENT sbname ANY>
<!ELEMENT sbentryl ANY>
<!ELEMENT sbentryr ANY>

<!ELEMENT mission ANY>
<!ELEMENT missiontitle ANY>
<!ELEMENT missionentry ANY>

<!ELEMENT leadrow (#PCDATA)>
<!ELEMENT row (#PCDATA)>

=== ziapeltagames/wrath-of-the-autarch/text/Skills and Stunts.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE Root SYSTEM "BookChapter.dtd">
<Root>     
    <Story>
        <chapter>Skills and Stunts</chapter> 
        <p1>Most actions taken by players involve skills and stunts. Typically, when the dice are rolled as part of an action, the result is added to an appropriate skill and compared against the opposition. Stunts provide additional effects that can modify how skills are used or provide special effects during different types of Conflicts.</p1>  
        <h1>Skills</h1> 
        <p1>Due to its Fate lineage, skills in <book>Wrath of the Autarch</book> are fairly broad descriptions of capabilities and areas of expertise. Skills are used in conjunction with the four core actions mentioned in the <chapref>Fate</chapref> chapter. Some skills are more suited to certain core actions than others (for instance, <skill>Science</skill> isn&apos;t usually used to Attack with). Every skill can be used with the Create Advantage and Overcome actions.</p1> 
        <p1>Since the only action types available in the Challenge Phase are Create an Advantage and Overcome, every skill could play a role in the Challenge Phase. The four types of Conflicts tend to focus on distinct skills. For instance, Tactics is very useful in Warfare, while Stealth is most useful during Infiltration. Knowing which skills are best for each Conflict is useful when determining which heroes to take on a mission. The skill description also describes what sorts of Conflicts a skill is best suited for.</p1> 
        <h1>Stunts</h1> 
        <p1>Stunts are special applications of skills, accessible when a skill reaches a certain level. They allow for additional bonuses to rolls, special benefits during certain Conflicts, or other advantages that go beyond the normal usages of a skill.</p1> 
        <h2>Gaining Stunts</h2> 
        <p1>When a skill reaches the rank of Great (+4), the player picks one of the stunts listed under the skill description and writes it on their character sheet. For each skill rank above Great (+4), the character gains one additional stunt. Some stunts have other stunts listed as preqrequisites. In that case, the stunt is not available until the character also has all the listed prerequisite stunts.</p1> 
        <p1>Since characters begin play with one skill at the rank of Great (+4), they also get one stunt from that skill.</p1>
        <h1>Athletics</h1> 
        <p1>Athletics encompasses not just physical fitness, but also body awareness and movement.  It is used for climbing, swimming, tumbling, and balancing.  If all that matters is raw power, and not some form of movement, then Physique is the more relevant skill.</p1> 
        <stuntt>Careful Movement</stuntt> 
        <stuntd>Step down the hinder die on any movement rolls.</stuntd> 
        <stuntt>Excellent Climber</stuntt> 
        <stuntd>Step up the help die on any rolls involving climbing.</stuntd> 
        <stuntt>Shifty Dodge</stuntt> 
        <stuntd>In a Skirmish, when using Athletics to defend against a Fighting attack, may move one zone away after the attack.</stuntd> 
        <stuntt>Roll with the Blow</stuntt> 
        <stuntp>Prerequisite: Shifty Dodge</stuntp> 
        <stuntd>In a Skirmish, when using Athletics to defend against a Fighting attack, may move two zones away after the attack</stuntd>  
        <h1>Channeling</h1> 
        <p1>Channeling is used to detect and harness the magic energies that can be found in the wildest regions of the Realm. Channeling is also used to determine the amount of starting mana a spellcaster has available to them. See the <chapref>Magic</chapref> chapter for more details on mana, spellcasting, and channeling.</p1> 
        <stuntt>Chaotic Reserves</stuntt>
        <stuntd>Bind to a Region and gain mana each season as a spellcaster (no changes if already a spellcaster). Spend one and only one mana on any roll to step up both the help and hinder die by one. No backlash with this ability.</stuntd>
        <stuntt>Land Give Me Strength</stuntt>
        <stuntd>Bind to a Region as a spellcaster. Destroy one resource from the bound region to step up the help die on any roll by two.</stuntd>
        <stuntt>Hurt the Ones You Love</stuntt>
        <stuntd>Reduce the amount of backlash rolled by six. In exchange, a character from the same faction as the caster must take a severe consequence. The character should be someone the caster cares about (the caster should have a relevant relationship aspect with the character who takes the consequence). If the target character doesn't have an open severe consequence slot, they are killed instead. The consequence should be thematically appropriate to the type of magic used.</stuntd>   
        <stuntt>The Land Weeps for My Pain</stuntt> 
        <stuntd>Bind to a Region as a spellcaster. Reduce the stress taken from any attack by one for each resource sacrificed from the land the character is bound to. Resources lost this way may not be recovered.</stuntd>              
        <h1>Deceive</h1> 
        <p1>Disguises, bluffing, and gambling are all practical applications of the Deceive skill. Any time lies are involved, the Deceive skill usually comes into play.</p1> 
        <stuntt>Blackmail Artist</stuntt> 
        <stuntd>Step up the help die on social rolls when the character is blackmailing the target.</stuntd> 
        <stuntt>Deep Cover</stuntt> 
        <stuntd>If captured during an Infiltration mission, the character may successfully shift blame to some other faction. Add a relevant permanent aspect to the target faction, indicating their growing distrust and animosity. Although the Stronghold takes no disposition hits, the caught character suffers all normal penalties (they could be detained or executed).</stuntd> 
        <stuntt>Trained Actor</stuntt> 
        <stuntd>Step up the help die when the character pretends to be someone they aren’t.</stuntd> 
        <stuntt>With Friends like These…</stuntt> 
        <stuntd>May use deceit even against characters with positive relationship aspects. Furthermore, step up the help die by one when lying to friends.</stuntd>
        <stuntd>However, on a failed roll, change the relationship aspect to something negative.</stuntd>         
        <h1>Empathy</h1> 
        <p1>Empathy is the ability to read another person&apos;s feelings. This is typically used to detect how honest another person is being, as well as getting a handle on their emotional state.</p1> 
        <stuntt>I Know a Bad Deal When I Hear It</stuntt> 
        <stuntd>Step up the help die on any rolls for recognizing a bad deal.</stuntd> 
        <stuntt>I’ve Sized You Up</stuntt> 
        <stuntd>Step up the help die when using the Create Advantage action to assess a character's emotional state.</stuntd> 
        <stuntt>Soothing Words</stuntt>
        <stuntd>By succeeding at an Empathy roll with a difficulty of Good (+3), may remove someone else's mild consequence related to being weary or psychologically troubled. This roll takes an action.</stuntd>
        <stuntt>You Don’t Love Me</stuntt> 
        <stuntd>Step up the help die when defending against being seduced.</stuntd>                
        <h1>Fighting</h1> 
        <p1>Fighting is knowledge of weapons and the ability to utilize them to defeat others in martial combat. It also covers unarmed combat. However, it isn’t used for leading units of many men into battle, which falls under the Tactics skill.</p1> 
        <stuntt>Favored Weapon</stuntt> 
        <stuntd>The character has extensive training with a particular weapon. Replace one of the character's aspects with an aspect describing their favored weapon (if they don't already have one). Step up the help die when using the favored weapon in combat.</stuntd> 
        <stuntt>Favored Weapon (Improved)</stuntt> 
        <stuntp>Requirement:  Favored Weapon</stuntp> 
        <stuntd>Step up the help die when using the favored weapon in combat.</stuntd> 
        <stuntt>I’m on a Roll!</stuntt> 
        <stuntp>Requirement: Favored Weapon</stuntp> 
        <stuntd>On a successful attack with the favored weapon, gain a boost even if didn't succeed with style. If succeeded with style, gain an extra free invoke.</stuntd>  
        <stuntt>No Quarter Given</stuntt>
        <stuntd>During Skirmish or Infiltration, force an opponent to make an opposed roll against your Fighting if they wish to leave the zone. May only be used once per exchange.</stuntd>       
        <stuntt>Whirling Attack</stuntt> 
        <stuntd>During Skirmish or Infiltration, may attack every opponent in the same zone with the same attack action, but must step up the hinder die once. Only roll the attack once, but each defender may defend individually.</stuntd> 
        <h1>Investigation</h1> 
        <p1>Investigation is the ability to corroborate evidence and interpret and analyze clues. A character with a high Investigation skill also knows who to talk to or where to go next.</p1> 
        <stuntt>Digging up Dirt</stuntt> 
        <stuntd>Any time Investigation is used to create an aspect that could be used for blackmail, step up the help die.</stuntd> 
        <stuntt>I’m a Good Detective…</stuntt> 
        <stuntd>Connect that dots that seem completely unrelated to the untrained eye. When using investigation to overcome a Challenge, the player may decide to take narrative control even on a successful roll.</stuntd> 
        <stuntt>…A Seriously Good Detective</stuntt> 
        <stuntp>Requirements: I’m a Good Detective…</stuntp> 
        <stuntd>After using I&apos;m a good detective, may spend a fate point to create a mission aspect.</stuntd> 
        <h1>Intimidation</h1>
